# -*- coding: utf-8 -*-
"""config.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ktzc3qCaDLE6tkDKuKRIoSLW7ULfjPib
"""

API_TOKEN = 

  # DEBUG_ID = '<YOUR_DEBUG_ID>'
  
  GET_DEBUG_INFO = False

  LOGGING = True

  MODE = 'NORMAL'

  CONNECTION_TYPE = 'POLLING'

  # WEBHOOK_HOST = '<YOUR_WEBHOOK_HOST>'

  # WEBAPP_PORT = '<YOUR_WEBAPP_PORT>'

"""Где:

<YOUR TOKEN> -- токен вашего бота, который можно получить у официального бота сервиса Telegram для создания собственных ботов: @BotFather,

<YOUR_DEBUG_ID> -- id человека, которому будут приходить сообщения в телеграм об ошибках,
GET_DEBUG_INFO -- будет ли на указанный выше id отправляться информация об ошибках (если поставить False, то можно не указывать id в строке выше),

LOGGING -- будет ли выводиться в консоль информация о том, какие действия сейчас совершает бот,

MODE -- может принимать значения 'EASY' или 'NORMAL', в первом случае при попытке перенесения стиля бот будет сообщать, что он запущен на слабом устройстве, во втором случае все работает штатно.

CONNECTION_TYPE -- может принимать значения 'POLLING' или 'WEBHOOKS', в зависимости от желаемого вами типа (для более простой работы стоит указать 'POLLING')

<YOUR_WEBHOOK_HOST> -- адрес вашего webhook хоста (если выше выбрали 'POLLING', то можно не заполнять)

<YOUR_WEBAPP_POST> -- порт вашего webhook хоста (если выше выбрали 'POLLING', то можно не заполнять)
"""

