# -*- coding: utf-8 -*-
"""Procfile.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NvW0QoCh2BTn1PTuzrEGKzYFIZ5liJi0
"""

worker: python main.py